module Ploeh.Numsense.SwissGermanhExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(        -1, "eis unger null")>]
[<InlineData(         0, "null")>]
[<InlineData(         1, "eis")>]
[<InlineData(         2, "zwöi")>]
[<InlineData(         3, "drü")>]
[<InlineData(         4, "vier")>]
[<InlineData(         5, "föif")>]
[<InlineData(         6, "sächs")>]
[<InlineData(         7, "sibe")>]
[<InlineData(         8, "acht")>]
[<InlineData(         9, "nün")>]
[<InlineData(        10, "zäh")>]
[<InlineData(        11, "öuf")>]
[<InlineData(        12, "zwöuf")>]
[<InlineData(        13, "drizäh")>]
[<InlineData(        14, "vierzäh")>]
[<InlineData(        15, "füfzäh")>]
[<InlineData(        16, "sächzäh")>]
[<InlineData(        17, "sibezäh")>]
[<InlineData(        18, "achtzäh")>]
[<InlineData(        19, "nünzäh")>]
[<InlineData(        20, "zwänzg")>]
[<InlineData(        21, "einezwänzg")>]
[<InlineData(        22, "zwöiezwänzg")>]
[<InlineData(        23, "drüezwänzg")>]
[<InlineData(        24, "vierezwänzg")>]
[<InlineData(        25, "föifezwänzg")>]
[<InlineData(        26, "sächsezwänzg")>]
[<InlineData(        27, "sibenezwänzg")>]
[<InlineData(        28, "achtezwänzg")>]
[<InlineData(        29, "nünezwänzg")>]
[<InlineData(        30, "drissg")>]
[<InlineData(        34, "vieredrissg")>]
[<InlineData(        40, "vierzg")>]
[<InlineData(        42, "zwöievierzg")>]
[<InlineData(        50, "füfzg")>]
[<InlineData(        58, "achtefüfzg")>]
[<InlineData(        60, "sächzg")>]
[<InlineData(        65, "föifesächzg")>]
[<InlineData(        70, "sibezg")>]
[<InlineData(        79, "nünesibezg")>]
[<InlineData(        80, "achtzg")>]
[<InlineData(        86, "sächsenachtzg")>]
[<InlineData(        90, "nünzg")>]
[<InlineData(        93, "drüenünzg")>]
[<InlineData(       100, "hundert")>]
[<InlineData(       101, "hunderteis")>]
[<InlineData(       110, "hundertzäh")>]
[<InlineData(       114, "hundertvierzäh")>]
[<InlineData(       135, "hundertföifedrissg")>]
[<InlineData(       200, "zwöihundert")>]
[<InlineData(       282, "zwöihundertzwöienachtzg")>]
[<InlineData(       331, "drühunderteinedrissg")>]
[<InlineData(       407, "vierhundertsibe")>]
[<InlineData(       520, "föifhundertzwänzg")>]
[<InlineData(       666, "sächshundertsächsesächzg")>]
[<InlineData(       798, "sibehundertachtenünzg")>]
[<InlineData(       857, "achthundertsibenefüfzg")>]
[<InlineData(       999, "nünhundertnünenünzg")>]
[<InlineData(      1000, "tusig")>]
[<InlineData(      1001, "tusigundeis")>]
[<InlineData(      1010, "tusigundzäh")>]
[<InlineData(      1066, "tusigundsächsesächzg")>]
[<InlineData(      1337, "tusigdrühundertsibenedrissg")>]
[<InlineData(      1984, "tusignünhundertvierenachtzg")>]
[<InlineData(      2015, "zwöitusigundfüfzäh")>]
[<InlineData(      3000, "drütusig")>]
[<InlineData(      3297, "drütusigzwöihundertsibenenünzg")>]
[<InlineData(      4080, "viertusigundachtzg")>]
[<InlineData(      5011, "föiftusigundöuf")>]
[<InlineData(      6025, "sächstusigundföifezwänzg")>]
[<InlineData(      7441, "sibetusigvierhunderteinevierzg")>]
[<InlineData(      8513, "achttusigföifhundertdrizäh")>]
[<InlineData(      9000, "nüntusig")>]
[<InlineData(     10000, "zähtusig")>]
[<InlineData(     12001, "zwöuftusigundeis")>]
[<InlineData(     23456, "drüezwänzgtusigvierhundertsächsefüfzg")>]
[<InlineData(     32109, "zwöiedrissgtusigeihundertnün")>]
[<InlineData(     40404, "vierzgtusigvierhundertvier")>]
[<InlineData(     56789, "sächsefüfzgtusigsibehundertnünenachtzg")>]
[<InlineData(     60015, "sächzgtusigundfüfzäh")>]
[<InlineData(     71003, "einesibezgtusigunddrü")>]
[<InlineData(     80522, "achtzgtusigföifhundertzwöiezwänzg")>]
[<InlineData(     98765, "achtenünzgtusigsibehundertföifesächzg")>]
[<InlineData(    100000, "hunderttusig")>]
[<InlineData(    100001, "hunderttusigundeis")>]
[<InlineData(    100010, "hunderttusigundzäh")>]
[<InlineData(    100100, "hunderttusigeihundert")>]
[<InlineData(    101010, "hunderteistusigundzäh")>]
[<InlineData(    200000, "zwöihunderttusig")>]
[<InlineData(    321000, "drühunderteinezwänzgtusig")>]
[<InlineData(    411416, "vierhundertöuftusigvierhundertsächzäh")>]
[<InlineData(    530121, "föifhundertdrissgtusigeihunderteinezwänzg")>]
[<InlineData(    600000, "sächshunderttusig")>]
[<InlineData(    788000, "sibehundertachtenachtzgtusig")>]
[<InlineData(    876540, "achthundertsächsesibezgtusigföifhundertvierzg")>]
[<InlineData(    908077, "nünhundertachttusigundsibenesibezg")>]
[<InlineData(   1000000, "ei Million")>]
[<InlineData(   1000001, "ei Million eis")>]      //TODO
[<InlineData(   1000100, "ei Million hundert")>]//TODO
[<InlineData(   1001000, "ei Million tusig")>]//TODO
[<InlineData(   1010000, "ei Million zähtusig")>]
[<InlineData(   2000002, "zwöi Millione zwöi")>]
[<InlineData(   3040506, "drü Millione vierzgtusigföifhundertsächs")>]
[<InlineData(   4321000, "vier Millione drühunderteinezwänzgtusig")>]
[<InlineData(   5004621, "föif Millione viertusigsächshunderteinezwänzg")>]
[<InlineData(   6982001, "sächs Millione nünhundertzwöienachtzgtusigundeis")>]
[<InlineData(   7000000, "sibe Millione")>]
[<InlineData(   8000220, "acht Millione zwöihundertzwänzg")>]
[<InlineData(   9099000, "nün Millione nünenünzgtusig")>]
[<InlineData(  10000000, "zäh Millione")>]
[<InlineData(  24000000, "vierezwänzg Millione")>]
[<InlineData(  39020011, "nünedrissg Millione zwänzgtusigundöuf")>]
[<InlineData(  40606100, "vierzg Millione sächshundertsächstusigeihundert")>]
[<InlineData(  53000000, "drüefüfzg Millione")>]
[<InlineData(  64000098, "vieresächzg Millione achtenünzg")>]
[<InlineData(  70003190, "sibezg Millione drütusigeihundertnünzg")>]
[<InlineData(  80000000, "achtzg Millione")>]
[<InlineData(  99000099, "nünenünzg Millione nünenünzg")>]
[<InlineData( 100000000, "hundert Millione")>]
[<InlineData( 209000000, "zwöihundertnün Millione")>]
[<InlineData( 398000000, "drühundertachtenünzg Millione")>]
[<InlineData( 439011000, "vierhundertnünedrissg Millione öuftusig")>]
[<InlineData( 560400000, "föifhundertsächzg Millione vierhunderttusig")>]
[<InlineData( 600010900, "sächshundert Millione zähtusignünhundert")>]
[<InlineData( 700000000, "sibehundert Millione")>]
[<InlineData( 800116000, "achthundert Millione hundertsächzähtusig")>]
[<InlineData( 900800007, "nünhundert Millione achthunderttusigundsibe")>]
[<InlineData(1000000000, "ei Milliarde")>]
[<InlineData(2121000000, "zwöi Milliarde hunderteinezwänzg Millione")>]
[<InlineData(System.Int32.MaxValue,
    "zwöi Milliarde hundertsibenevierzg Millione vierhundertdrüenachtzgtusigsächshundertsibenevierzg")>]

let ``toBernese returns correct result`` (i, expected) =
    let actual = Numeral.toBernese i
    expected =! actual
