module Ploeh.Numsense.SwissGermanhExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                  "eis unger null",       -1)>]
[<InlineData(                                            "null",        0)>]
[<InlineData(                                           " null",        0)>]
[<InlineData(                                           "null ",        0)>]
[<InlineData(                                        "  null  ",        0)>]
[<InlineData(                                            "Null",        0)>]
[<InlineData(                                            "NULL",        0)>]
[<InlineData(                                         " nULl\t",        0)>]
[<InlineData(                                            "null",        0)>]
[<InlineData(                                             "eis",        1)>]
[<InlineData(                                            "zwöi",        2)>]
[<InlineData(                                             "drü",        3)>]
[<InlineData(                                            "vier",        4)>]
[<InlineData(                                            "föif",        5)>]
[<InlineData(                                           "sächs",        6)>]
[<InlineData(                                            "sibe",        7)>]
[<InlineData(                                            "acht",        8)>]
[<InlineData(                                             "nün",        9)>]
[<InlineData(                                             "zäh",       10)>]
[<InlineData(                                             "öuf",       11)>]
[<InlineData(                                           "zwöuf",       12)>]
[<InlineData(                                          "drizäh",       13)>]
[<InlineData(                                         "vierzäh",       14)>]
[<InlineData(                                          "füfzäh",       15)>]
[<InlineData(                                         "sächzäh",       16)>]
[<InlineData(                                         "sibezäh",       17)>]
[<InlineData(                                         "achtzäh",       18)>]
[<InlineData(                                          "nünzäh",       19)>]
[<InlineData(                                          "zwänzg",       20)>]
[<InlineData(                                      "einezwänzg",       21)>]
[<InlineData(                                     "zwöiezwänzg",       22)>]
[<InlineData(                                      "drüezwänzg",       23)>]
[<InlineData(                                     "vierezwänzg",       24)>]
[<InlineData(                                     "föifezwänzg",       25)>]
[<InlineData(                                    "sächsezwänzg",       26)>]
[<InlineData(                                    "sibenezwänzg",       27)>]
[<InlineData(                                     "achtezwänzg",       28)>]
[<InlineData(                                      "nünezwänzg",       29)>]
[<InlineData(                                          "drissg",       30)>]
[<InlineData(                                     "vieredrissg",       34)>]
[<InlineData(                                          "vierzg",       40)>]
[<InlineData(                                     "zwöievierzg",       42)>]
[<InlineData(                                           "füfzg",       50)>]
[<InlineData(                                      "achtefüfzg",       58)>]
[<InlineData(                                          "sächzg",       60)>]
[<InlineData(                                     "föifesächzg",       65)>]
[<InlineData(                                          "sibezg",       70)>]
[<InlineData(                                      "nünesibezg",       79)>]
[<InlineData(                                          "achtzg",       80)>]
[<InlineData(                                   "sächsenachtzg",       86)>]
[<InlineData(                                           "nünzg",       90)>]
[<InlineData(                                       "drüenünzg",       93)>]
[<InlineData(                                         "hundert",      100)>]
[<InlineData(                                      "hunderteis",      101)>]
[<InlineData(                                      "hundertzäh",      110)>]
[<InlineData(                                  "hundertvierzäh",      114)>]
[<InlineData(                              "hundertföifedrissg",      135)>]
[<InlineData(                                     "zwöihundert",      200)>]
[<InlineData(                         "zwöihundertzwöienachtzg",      282)>]
[<InlineData(                            "drühunderteinedrissg",      331)>]
[<InlineData(                                 "vierhundertsibe",      407)>]
[<InlineData(                               "föifhundertzwänzg",      520)>]
[<InlineData(                        "sächshundertsächsesächzg",      666)>]
[<InlineData(                           "sibehundertachtenünzg",      798)>]
[<InlineData(                          "achthundertsibenefüfzg",      857)>]
[<InlineData(                             "nünhundertnünenünzg",      999)>]
[<InlineData(                                           "tusig",     1000)>]
[<InlineData(                                     "tusigundeis",     1001)>]
[<InlineData(                                     "tusigundzäh",     1010)>]
[<InlineData(                            "tusigundsächsesächzg",     1066)>]
[<InlineData(                     "tusigdrühundertsibenedrissg",     1337)>]
[<InlineData(                     "tusignünhundertvierenachtzg",     1984)>]
[<InlineData(                              "zwöitusigundfüfzäh",     2015)>]
[<InlineData(                                        "drütusig",     3000)>]
[<InlineData(                  "drütusigzwöihundertsibenenünzg",     3297)>]
[<InlineData(                              "viertusigundachtzg",     4080)>]
[<InlineData(                                 "föiftusigundöuf",     5011)>]
[<InlineData(                        "sächstusigundföifezwänzg",     6025)>]
[<InlineData(                  "sibetusigvierhunderteinevierzg",     7441)>]
[<InlineData(                      "achttusigföifhundertdrizäh",     8513)>]
[<InlineData(                                        "nüntusig",     9000)>]
[<InlineData(                                        "zähtusig",    10000)>]
[<InlineData(                                "zwöuftusigundeis",    12001)>]
[<InlineData(           "drüezwänzgtusigvierhundertsächsefüfzg",    23456)>]
[<InlineData(                    "zwöiedrissgtusigeihundertnün",    32109)>]
[<InlineData(                      "vierzgtusigvierhundertvier",    40404)>]
[<InlineData(          "sächsefüfzgtusigsibehundertnünenachtzg",    56789)>]
[<InlineData(                            "sächzgtusigundfüfzäh",    60015)>]
[<InlineData(                           "einesibezgtusigunddrü",    71003)>]
[<InlineData(               "achtzgtusigföifhundertzwöiezwänzg",    80522)>]
[<InlineData(           "achtenünzgtusigsibehundertföifesächzg",    98765)>]
[<InlineData(                                    "hunderttusig",   100000)>]
[<InlineData(                              "hunderttusigundeis",   100001)>]
[<InlineData(                              "hunderttusigundzäh",   100010)>]
[<InlineData(                           "hunderttusigeihundert",   100100)>]
[<InlineData(                           "hunderteistusigundzäh",   101010)>]
[<InlineData(                                "zwöihunderttusig",   200000)>]
[<InlineData(                       "drühunderteinezwänzgtusig",   321000)>]
[<InlineData(           "vierhundertöuftusigvierhundertsächzäh",   411416)>]
[<InlineData(       "föifhundertdrissgtusigeihunderteinezwänzg",   530121)>]
[<InlineData(                               "sächshunderttusig",   600000)>]
[<InlineData(                    "sibehundertachtenachtzgtusig",   788000)>]
[<InlineData(   "achthundertsächsesibezgtusigföifhundertvierzg",   876540)>]
[<InlineData(              "nünhundertachttusigundsibenesibezg",   908077)>]
[<InlineData(                                      "ei Million",  1000000)>]
[<InlineData(                                  "ei Million eis",  1000001)>]      //TODO
[<InlineData(                              "ei Million hundert",  1000100)>]//TODO
[<InlineData(                                "ei Million tusig",  1001000)>]//TODO
[<InlineData(                             "ei Million zähtusig",  1010000)>]
[<InlineData(                              "zwöi Millione zwöi",  2000002)>]
[<InlineData(        "drü Millione vierzgtusigföifhundertsächs",  3040506)>]
[<InlineData(         "vier Millione drühunderteinezwänzgtusig",  4321000)>]
[<InlineData(   "föif Millione viertusigsächshunderteinezwänzg",  5004621)>]
[<InlineData("sächs Millione nünhundertzwöienachtzgtusigundeis",  6982001)>]
[<InlineData(                                   "sibe Millione",  7000000)>]
[<InlineData(                 "acht Millione zwöihundertzwänzg",  8000220)>]
[<InlineData(                     "nün Millione nünenünzgtusig",  9099000)>]
[<InlineData(                                    "zäh Millione",  10000000)>]
[<InlineData(                            "vierezwänzg Millione",  24000000)>]
[<InlineData(           "nünedrissg Millione zwänzgtusigundöuf",  39020011)>]
[<InlineData( "vierzg Millione sächshundertsächstusigeihundert",  40606100)>]
[<InlineData(                              "drüefüfzg Millione",  53000000)>]
[<InlineData(                 "vieresächzg Millione achtenünzg",  64000098)>]
[<InlineData(          "sibezg Millione drütusigeihundertnünzg",  70003190)>]
[<InlineData(                                 "achtzg Millione",  80000000)>]
[<InlineData(                    "nünenünzg Millione nünenünzg",  99000099)>]
[<InlineData(                                "hundert Millione", 100000000)>]
[<InlineData(                         "zwöihundertnün Millione", 209000000)>]
[<InlineData(                   "drühundertachtenünzg Millione", 398000000)>]
[<InlineData(         "vierhundertnünedrissg Millione öuftusig", 439011000)>]
[<InlineData(     "föifhundertsächzg Millione vierhunderttusig", 560400000)>]
[<InlineData(        "sächshundert Millione zähtusignünhundert", 600010900)>]
[<InlineData(                            "sibehundert Millione", 700000000)>]
[<InlineData(        "achthundert Millione hundertsächzähtusig", 800116000)>]
[<InlineData(     "nünhundert Millione achthunderttusigundsibe", 900800007)>]
[<InlineData(                                    "ei Milliarde",1000000000)>]
[<InlineData(       "zwöi Milliarde hunderteinezwänzg Millione",2121000000)>]
[<InlineData(
    "zwöi Milliarde hundertsibenevierzg Millione vierhundertdrüenachtzgtusigsächshundertsibenevierzg",
    System.Int32.MaxValue)>]
    
let ``tryParseBernese returns correct result`` (bernese, expected) =
    let actual = Numeral.tryParseBernese bernese
    Some expected =! actual

    
[<Theory>]
[<InlineData(        -1, "eis unger null")>]
[<InlineData(         0, "null")>]
[<InlineData(         1, "eis")>]
[<InlineData(         2, "zwöi")>]
[<InlineData(         3, "drü")>]
[<InlineData(         4, "vier")>]
[<InlineData(         5, "föif")>]
[<InlineData(         6, "sächs")>]
[<InlineData(         7, "sibe")>]
[<InlineData(         8, "acht")>]
[<InlineData(         9, "nün")>]
[<InlineData(        10, "zäh")>]
[<InlineData(        11, "öuf")>]
[<InlineData(        12, "zwöuf")>]
[<InlineData(        13, "drizäh")>]
[<InlineData(        14, "vierzäh")>]
[<InlineData(        15, "füfzäh")>]
[<InlineData(        16, "sächzäh")>]
[<InlineData(        17, "sibezäh")>]
[<InlineData(        18, "achtzäh")>]
[<InlineData(        19, "nünzäh")>]
[<InlineData(        20, "zwänzg")>]
[<InlineData(        21, "einezwänzg")>]
[<InlineData(        22, "zwöiezwänzg")>]
[<InlineData(        23, "drüezwänzg")>]
[<InlineData(        24, "vierezwänzg")>]
[<InlineData(        25, "föifezwänzg")>]
[<InlineData(        26, "sächsezwänzg")>]
[<InlineData(        27, "sibenezwänzg")>]
[<InlineData(        28, "achtezwänzg")>]
[<InlineData(        29, "nünezwänzg")>]
[<InlineData(        30, "drissg")>]
[<InlineData(        34, "vieredrissg")>]
[<InlineData(        40, "vierzg")>]
[<InlineData(        42, "zwöievierzg")>]
[<InlineData(        50, "füfzg")>]
[<InlineData(        58, "achtefüfzg")>]
[<InlineData(        60, "sächzg")>]
[<InlineData(        65, "föifesächzg")>]
[<InlineData(        70, "sibezg")>]
[<InlineData(        79, "nünesibezg")>]
[<InlineData(        80, "achtzg")>]
[<InlineData(        86, "sächsenachtzg")>]
[<InlineData(        90, "nünzg")>]
[<InlineData(        93, "drüenünzg")>]
[<InlineData(       100, "hundert")>]
[<InlineData(       101, "hunderteis")>]
[<InlineData(       110, "hundertzäh")>]
[<InlineData(       114, "hundertvierzäh")>]
[<InlineData(       135, "hundertföifedrissg")>]
[<InlineData(       200, "zwöihundert")>]
[<InlineData(       282, "zwöihundertzwöienachtzg")>]
[<InlineData(       331, "drühunderteinedrissg")>]
[<InlineData(       407, "vierhundertsibe")>]
[<InlineData(       520, "föifhundertzwänzg")>]
[<InlineData(       666, "sächshundertsächsesächzg")>]
[<InlineData(       798, "sibehundertachtenünzg")>]
[<InlineData(       857, "achthundertsibenefüfzg")>]
[<InlineData(       999, "nünhundertnünenünzg")>]
[<InlineData(      1000, "tusig")>]
[<InlineData(      1001, "tusigundeis")>]
[<InlineData(      1010, "tusigundzäh")>]
[<InlineData(      1066, "tusigundsächsesächzg")>]
[<InlineData(      1337, "tusigdrühundertsibenedrissg")>]
[<InlineData(      1984, "tusignünhundertvierenachtzg")>]
[<InlineData(      2015, "zwöitusigundfüfzäh")>]
[<InlineData(      3000, "drütusig")>]
[<InlineData(      3297, "drütusigzwöihundertsibenenünzg")>]
[<InlineData(      4080, "viertusigundachtzg")>]
[<InlineData(      5011, "föiftusigundöuf")>]
[<InlineData(      6025, "sächstusigundföifezwänzg")>]
[<InlineData(      7441, "sibetusigvierhunderteinevierzg")>]
[<InlineData(      8513, "achttusigföifhundertdrizäh")>]
[<InlineData(      9000, "nüntusig")>]
[<InlineData(     10000, "zähtusig")>]
[<InlineData(     12001, "zwöuftusigundeis")>]
[<InlineData(     23456, "drüezwänzgtusigvierhundertsächsefüfzg")>]
[<InlineData(     32109, "zwöiedrissgtusigeihundertnün")>]
[<InlineData(     40404, "vierzgtusigvierhundertvier")>]
[<InlineData(     56789, "sächsefüfzgtusigsibehundertnünenachtzg")>]
[<InlineData(     60015, "sächzgtusigundfüfzäh")>]
[<InlineData(     71003, "einesibezgtusigunddrü")>]
[<InlineData(     80522, "achtzgtusigföifhundertzwöiezwänzg")>]
[<InlineData(     98765, "achtenünzgtusigsibehundertföifesächzg")>]
[<InlineData(    100000, "hunderttusig")>]
[<InlineData(    100001, "hunderttusigundeis")>]
[<InlineData(    100010, "hunderttusigundzäh")>]
[<InlineData(    100100, "hunderttusigeihundert")>]
[<InlineData(    101010, "hunderteistusigundzäh")>]
[<InlineData(    200000, "zwöihunderttusig")>]
[<InlineData(    321000, "drühunderteinezwänzgtusig")>]
[<InlineData(    411416, "vierhundertöuftusigvierhundertsächzäh")>]
[<InlineData(    530121, "föifhundertdrissgtusigeihunderteinezwänzg")>]
[<InlineData(    600000, "sächshunderttusig")>]
[<InlineData(    788000, "sibehundertachtenachtzgtusig")>]
[<InlineData(    876540, "achthundertsächsesibezgtusigföifhundertvierzg")>]
[<InlineData(    908077, "nünhundertachttusigundsibenesibezg")>]
[<InlineData(   1000000, "ei Million")>]
[<InlineData(   1000001, "ei Million eis")>]      //TODO
[<InlineData(   1000100, "ei Million hundert")>]//TODO
[<InlineData(   1001000, "ei Million tusig")>]//TODO
[<InlineData(   1010000, "ei Million zähtusig")>]
[<InlineData(   2000002, "zwöi Millione zwöi")>]
[<InlineData(   3040506, "drü Millione vierzgtusigföifhundertsächs")>]
[<InlineData(   4321000, "vier Millione drühunderteinezwänzgtusig")>]
[<InlineData(   5004621, "föif Millione viertusigsächshunderteinezwänzg")>]
[<InlineData(   6982001, "sächs Millione nünhundertzwöienachtzgtusigundeis")>]
[<InlineData(   7000000, "sibe Millione")>]
[<InlineData(   8000220, "acht Millione zwöihundertzwänzg")>]
[<InlineData(   9099000, "nün Millione nünenünzgtusig")>]
[<InlineData(  10000000, "zäh Millione")>]
[<InlineData(  24000000, "vierezwänzg Millione")>]
[<InlineData(  39020011, "nünedrissg Millione zwänzgtusigundöuf")>]
[<InlineData(  40606100, "vierzg Millione sächshundertsächstusigeihundert")>]
[<InlineData(  53000000, "drüefüfzg Millione")>]
[<InlineData(  64000098, "vieresächzg Millione achtenünzg")>]
[<InlineData(  70003190, "sibezg Millione drütusigeihundertnünzg")>]
[<InlineData(  80000000, "achtzg Millione")>]
[<InlineData(  99000099, "nünenünzg Millione nünenünzg")>]
[<InlineData( 100000000, "hundert Millione")>]
[<InlineData( 209000000, "zwöihundertnün Millione")>]
[<InlineData( 398000000, "drühundertachtenünzg Millione")>]
[<InlineData( 439011000, "vierhundertnünedrissg Millione öuftusig")>]
[<InlineData( 560400000, "föifhundertsächzg Millione vierhunderttusig")>]
[<InlineData( 600010900, "sächshundert Millione zähtusignünhundert")>]
[<InlineData( 700000000, "sibehundert Millione")>]
[<InlineData( 800116000, "achthundert Millione hundertsächzähtusig")>]
[<InlineData( 900800007, "nünhundert Millione achthunderttusigundsibe")>]
[<InlineData(1000000000, "ei Milliarde")>]
[<InlineData(2121000000, "zwöi Milliarde hunderteinezwänzg Millione")>]
[<InlineData(System.Int32.MaxValue,
    "zwöi Milliarde hundertsibenevierzg Millione vierhundertdrüenachtzgtusigsächshundertsibenevierzg")>]

let ``toBernese returns correct result`` (i, expected) =
    let actual = Numeral.toBernese i
    expected =! actual
